import FadeIn from '../components/FadeIn';

const DisclaimerPage = () => {
  return (
    <section className="py-24 bg-altBackground relative overflow-hidden min-h-screen">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <FadeIn direction="up">
          <div className="mb-12 text-center">
            <h1 className="text-3xl md:text-5xl font-bold font-heading mb-6 text-textColor tracking-tight">
              Legal <span className="text-primary">Disclaimer</span>
            </h1>
            <p className="text-gray-500">Last updated: {new Date().toLocaleDateString('en-IN', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
          </div>
          
          <div className="bg-white/80 dark:bg-slate-800/80 backdrop-blur-md p-8 sm:p-12 rounded-3xl shadow-premium border border-gray-100/80 dark:border-white/10 space-y-8 text-gray-700 dark:text-gray-300">
            
            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">1. Not Legal or Medical Advice</h2>
              <p className="leading-relaxed mb-4">
                SimplyAbled is a software platform designed to assist special education professionals in organizing and drafting educational documentation.
              </p>
              <div className="bg-rose-50 dark:bg-rose-500/10 p-6 rounded-xl border border-rose-100 dark:border-rose-500/20">
                <p className="leading-relaxed text-sm font-semibold text-rose-800 dark:text-rose-300">
                  The content generated by SimplyAbled does NOT constitute legal, medical, or diagnostic advice. Our platform is not a substitute for the professional judgment of qualified educators, psychologists, therapists, or medical practitioners.
                </p>
              </div>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">2. AI Generation Limitations</h2>
              <p className="leading-relaxed mb-4">
                SimplyAbled utilizes artificial intelligence (AI) to generate drafts of Individualized Education Programs (IEPs), lesson plans, and other related documents based on the inputs you provide. 
              </p>
              <ul className="list-disc pl-5 space-y-2 text-sm leading-relaxed">
                <li>AI models can occasionally hallucinate, omit information, or generate text that is not fully compliant with local educational standards.</li>
                <li><strong>All generated documents are DRAFTS.</strong> They must be thoroughly reviewed, verified, and edited by a qualified professional before being finalized or presented to parents, schools, or governmental bodies.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">3. Compliance Responsibility</h2>
              <p className="leading-relaxed">
                While we strive to format documents in a way that generally aligns with standard practices (e.g., IDEA compliance in the USA or relevant local Indian guidelines), it is solely the responsibility of the user to ensure that the final document complies with their specific school district, state, or national laws and regulations. SimplyAbled assumes no liability for compliance failures.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">4. "As Is" Service</h2>
              <p className="leading-relaxed">
                The SimplyAbled platform is provided on an "as is" and "as available" basis without any warranties of any kind, whether express or implied. We do not warrant that the platform will be uninterrupted, entirely error-free, or completely secure.
              </p>
            </div>

          </div>
        </FadeIn>
      </div>
    </section>
  );
};

export default DisclaimerPage;
