import FadeIn from '../components/FadeIn';

const PrivacyPolicyPage = () => {
  return (
    <section className="py-24 bg-altBackground relative overflow-hidden min-h-screen">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <FadeIn direction="up">
          <div className="mb-12 text-center">
            <h1 className="text-3xl md:text-5xl font-bold font-heading mb-6 text-textColor tracking-tight">
              Privacy <span className="text-primary">Policy</span>
            </h1>
            <p className="text-gray-500">Last updated: {new Date().toLocaleDateString('en-IN', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
          </div>
          
          <div className="bg-white/80 dark:bg-slate-800/80 backdrop-blur-md p-8 sm:p-12 rounded-3xl shadow-premium border border-gray-100/80 dark:border-white/10 space-y-10 text-gray-700 dark:text-gray-300">
            
            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">1. Introduction</h2>
              <p className="leading-relaxed">
                Welcome to SimplyAbled. We respect your privacy and are committed to protecting your personal data. This Privacy Policy explains how we collect, use, store, and process your information when you use our SaaS platform. This policy complies with the Information Technology Act, 2000, and the Digital Personal Data Protection Act, 2023 (DPDP Act) of India.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">2. Data Collection & Usage</h2>
              <div className="space-y-4">
                <div className="bg-gray-50 dark:bg-slate-900/50 p-6 rounded-xl border border-gray-100 dark:border-slate-700">
                  <h3 className="font-bold text-gray-900 dark:text-white mb-2">Information We Collect</h3>
                  <ul className="list-disc pl-5 space-y-2 text-sm">
                    <li><strong>Account Data:</strong> Name, email address, and authentication credentials.</li>
                    <li><strong>Usage Data:</strong> Information about how you use our application, including timestamps, IP addresses, and device identifiers.</li>
                    <li><strong>User-Generated Content:</strong> The inputs you provide for generating educational documents (IEPs, lesson plans, etc.).</li>
                  </ul>
                </div>
                <div className="bg-gray-50 dark:bg-slate-900/50 p-6 rounded-xl border border-gray-100 dark:border-slate-700">
                  <h3 className="font-bold text-gray-900 dark:text-white mb-2">How We Use Your Data</h3>
                  <ul className="list-disc pl-5 space-y-2 text-sm">
                    <li>To provide, maintain, and improve the SimplyAbled platform.</li>
                    <li>To authenticate your identity and secure your account.</li>
                    <li>To generate AI-assisted educational documents based strictly on your inputs.</li>
                  </ul>
                </div>
              </div>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">3. Data Protection & Security</h2>
              <p className="leading-relaxed mb-4">
                We implement industry-standard encryption protocols (including SSL/TLS) and strict access controls to protect your personal data and the sensitive educational data you process through our platform.
              </p>
              <p className="leading-relaxed font-semibold text-primary">
                SimplyAbled does NOT sell, rent, or trade your personal data to any third parties under any circumstances.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">4. Intellectual Property & Document Ownership</h2>
              <p className="leading-relaxed">
                Any educational documents, assessments, or plans generated by you using the SimplyAbled platform remain entirely your intellectual property. We claim no ownership over your user-generated content. You grant us a temporary, limited license solely to process the data to generate your requested outputs.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">5. User Rights (Under DPDP Act, 2023)</h2>
              <p className="leading-relaxed mb-4">
                As an Indian citizen, you possess specific rights regarding your digital personal data:
              </p>
              <ul className="list-disc pl-5 space-y-2 text-sm">
                <li><strong>Right to Information:</strong> You can request a summary of the personal data we hold about you.</li>
                <li><strong>Right to Correction & Erasure:</strong> You can ask us to update inaccurate data or delete your data entirely.</li>
                <li><strong>Right to Grievance Redressal:</strong> You have the right to register a complaint if your data is mishandled.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">6. Contact Information</h2>
              <p className="leading-relaxed mb-4">
                If you have any questions about this Privacy Policy or wish to exercise your data rights, please contact our Data Protection Officer at:
              </p>
              <div className="bg-orange-50 dark:bg-orange-500/10 p-6 rounded-xl border border-orange-100 dark:border-orange-500/20 text-sm">
                <p><strong>Company Name:</strong> [Your Company Name]</p>
                <p><strong>Registered Address:</strong> [Your Registered Address, City, State, ZIP, India]</p>
                <p><strong>Support Email:</strong> [support@simplyabled.com]</p>
                <p><strong>CIN (if applicable):</strong> [Your Corporate Identification Number]</p>
              </div>
            </div>

          </div>
        </FadeIn>
      </div>
    </section>
  );
};

export default PrivacyPolicyPage;
