import FadeIn from '../components/FadeIn';

const TermsConditionsPage = () => {
  return (
    <section className="py-24 bg-altBackground relative overflow-hidden min-h-screen">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <FadeIn direction="up">
          <div className="mb-12 text-center">
            <h1 className="text-3xl md:text-5xl font-bold font-heading mb-6 text-textColor tracking-tight">
              Terms & <span className="text-primary">Conditions</span>
            </h1>
            <p className="text-gray-500">Last updated: {new Date().toLocaleDateString('en-IN', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
          </div>
          
          <div className="bg-white/80 dark:bg-slate-800/80 backdrop-blur-md p-8 sm:p-12 rounded-3xl shadow-premium border border-gray-100/80 dark:border-white/10 space-y-10 text-gray-700 dark:text-gray-300">
            
            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">1. Agreement to Terms</h2>
              <p className="leading-relaxed">
                By accessing or using the SimplyAbled platform, you agree to be bound by these Terms & Conditions. If you disagree with any part of these terms, you may not access our service. This agreement is governed by the laws of India.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">2. Account Registration & Subscriptions</h2>
              <ul className="list-disc pl-5 space-y-2 text-sm leading-relaxed">
                <li>You must provide accurate, complete, and current information when creating an account.</li>
                <li>You are responsible for safeguarding your account password.</li>
                <li>Some features are billed on a subscription basis. You will be billed in advance on a recurring schedule based on the plan you select.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">3. AI-Generated Content Disclaimer</h2>
              <div className="bg-orange-50 dark:bg-orange-500/10 p-6 rounded-xl border border-orange-100 dark:border-orange-500/20">
                <p className="leading-relaxed text-sm font-medium">
                  <strong>IMPORTANT:</strong> SimplyAbled utilizes artificial intelligence to assist in the drafting of educational documents (such as IEPs and lesson plans). The generated content is intended strictly as a drafting assistant. <span className="text-primary font-bold">You acknowledge that AI-generated content must always be reviewed, verified, and modified by a qualified special education professional before any official use.</span> SimplyAbled is not responsible for errors, omissions, or compliance failures resulting from unreviewed AI outputs.
                </p>
              </div>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">4. Intellectual Property</h2>
              <p className="leading-relaxed mb-4">
                The SimplyAbled platform, including its original code, features, functionality, and branding, is owned by SimplyAbled and is protected by copyright, trademark, and other intellectual property laws of India.
              </p>
              <p className="leading-relaxed">
                However, <strong>all documents generated by you using our platform remain your exclusive property.</strong>
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">5. Acceptable Use Policy</h2>
              <p className="leading-relaxed mb-4">You agree not to use the platform to:</p>
              <ul className="list-disc pl-5 space-y-2 text-sm">
                <li>Violate any local, state, national, or international law or regulation.</li>
                <li>Submit personally identifiable information (PII) of students beyond what is minimally required, and you must ensure you have parental consent to process such data if required by law.</li>
                <li>Attempt to breach or bypass the platform's security measures.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">6. Limitation of Liability</h2>
              <p className="leading-relaxed">
                In no event shall SimplyAbled, its directors, employees, or partners, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the platform.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">7. Termination</h2>
              <p className="leading-relaxed">
                We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach these Terms. Upon termination, your right to use the Service will immediately cease.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">8. Governing Law & Dispute Resolution</h2>
              <p className="leading-relaxed mb-4">
                These Terms shall be governed and construed in accordance with the laws of India. Any disputes arising out of or relating to these terms will be subject to the exclusive jurisdiction of the courts located in [Your City, State], India.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">9. Contact Us</h2>
              <div className="bg-gray-50 dark:bg-slate-900/50 p-6 rounded-xl border border-gray-100 dark:border-slate-700 text-sm">
                <p><strong>Company Name:</strong> [Your Company Name]</p>
                <p><strong>Registered Address:</strong> [Your Registered Address, City, State, ZIP, India]</p>
                <p><strong>Support Email:</strong> [support@simplyabled.com]</p>
                <p><strong>GST Number:</strong> [Your GST Number, if applicable]</p>
              </div>
            </div>

          </div>
        </FadeIn>
      </div>
    </section>
  );
};

export default TermsConditionsPage;
