import FadeIn from './FadeIn';

const DocumentPreview = () => {
  return (
    <section className="py-24 bg-altBackground relative overflow-hidden">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <FadeIn direction="up">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-5xl font-bold font-heading mb-4 text-textColor">Professional Output. Instantly.</h2>
            <p className="text-xl text-gray-500">Take a look at the quality of documents generated by SimplyAbled.</p>
          </div>
        </FadeIn>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* IEP Preview */}
          <FadeIn delay={100} direction="up" className="relative group perspective-1000">
            <div className="bg-white p-6 rounded-2xl shadow-[0_15px_40px_-15px_rgba(0,0,0,0.1)] border border-gray-200 aspect-[8.5/11] transform transition-transform duration-500 group-hover:-rotate-2 group-hover:scale-105 flex flex-col relative overflow-hidden">
              <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-primary to-secondary"></div>
              <div className="mb-6 mt-2 border-b border-gray-100 pb-4">
                <h3 className="text-xl font-bold font-heading text-gray-800">IEP Goal Draft</h3>
                <p className="text-xs text-gray-400 mt-1">Student: J.D. | Grade: 3rd</p>
              </div>
              <div className="space-y-4 flex-1">
                <div>
                  <h4 className="text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-1">Present Levels</h4>
                  <p className="text-xs text-gray-600 leading-relaxed bg-gray-50 p-2 rounded">
                    J.D. is currently reading at a mid-1st grade level. He struggles with decoding multisyllabic words and identifying main ideas in grade-level texts.
                  </p>
                </div>
                <div>
                  <h4 className="text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-1">Annual Goal</h4>
                  <p className="text-xs text-gray-600 leading-relaxed bg-primary/5 p-2 rounded text-primary font-medium">
                    By October 2027, when given a 3rd-grade level text, J.D. will accurately decode multisyllabic words and state the main idea with 80% accuracy in 4 out of 5 consecutive trials.
                  </p>
                </div>
              </div>
            </div>
          </FadeIn>

          {/* Lesson Plan Preview */}
          <FadeIn delay={200} direction="up" className="relative group perspective-1000 mt-8 md:mt-0">
            <div className="bg-white p-6 rounded-2xl shadow-[0_15px_40px_-15px_rgba(0,0,0,0.1)] border border-gray-200 aspect-[8.5/11] transform transition-transform duration-500 group-hover:rotate-1 group-hover:scale-105 flex flex-col relative overflow-hidden">
              <div className="absolute top-0 left-0 w-full h-2 bg-blue-500"></div>
              <div className="mb-6 mt-2 border-b border-gray-100 pb-4">
                <h3 className="text-xl font-bold font-heading text-gray-800">Math Lesson Plan</h3>
                <p className="text-xs text-gray-400 mt-1">Topic: Fractions | Duration: 45m</p>
              </div>
              <div className="space-y-4 flex-1">
                <div>
                  <h4 className="text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-1">Objective</h4>
                  <p className="text-xs text-gray-600 leading-relaxed bg-gray-50 p-2 rounded">
                    Students will be able to identify and create equivalent fractions using visual models (fraction bars and pie charts).
                  </p>
                </div>
                <div>
                  <h4 className="text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-1">Accommodations</h4>
                  <ul className="text-xs text-gray-600 space-y-1 bg-blue-50/50 p-2 rounded">
                    <li>• Provide physical fraction manipulatives</li>
                    <li>• Allow verbal responses instead of written</li>
                    <li>• Extended time for independent practice (1.5x)</li>
                  </ul>
                </div>
              </div>
            </div>
          </FadeIn>

          {/* Progress Report Preview */}
          <FadeIn delay={300} direction="up" className="relative group perspective-1000 mt-8 md:mt-0">
            <div className="bg-white p-6 rounded-2xl shadow-[0_15px_40px_-15px_rgba(0,0,0,0.1)] border border-gray-200 aspect-[8.5/11] transform transition-transform duration-500 group-hover:-rotate-1 group-hover:scale-105 flex flex-col relative overflow-hidden">
              <div className="absolute top-0 left-0 w-full h-2 bg-green-500"></div>
              <div className="mb-6 mt-2 border-b border-gray-100 pb-4">
                <h3 className="text-xl font-bold font-heading text-gray-800">Progress Report</h3>
                <p className="text-xs text-gray-400 mt-1">Term: Q1 | Goal: Social Skills</p>
              </div>
              <div className="space-y-4 flex-1">
                <div>
                  <h4 className="text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-1">Data Summary</h4>
                  <p className="text-xs text-gray-600 leading-relaxed bg-gray-50 p-2 rounded">
                    Data collected over the past 9 weeks indicates that Sarah has successfully initiated interactions with peers in 65% of recorded opportunities (baseline: 30%).
                  </p>
                </div>
                <div>
                  <h4 className="text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-1">Narrative</h4>
                  <p className="text-xs text-gray-600 leading-relaxed bg-green-50/50 p-2 rounded">
                    Sarah has made excellent progress this quarter. She is consistently utilizing her "social script" cards during unstructured recess time. We will continue to fade physical prompts as she approaches her 80% mastery goal.
                  </p>
                </div>
              </div>
            </div>
          </FadeIn>
        </div>
      </div>
    </section>
  );
};

export default DocumentPreview;
